Cargo.toml
src/main.rs

feat: initialize cargo

---

.github/workflows/fmt.yml

ci: add format check

---

.github/workflows/cargo.yml

ci: add test and miri

---

tachyon-core/misc/config.toml
tachyon-docker/Dockerfile
tachyon-docker/docker-compose.yml
tachyon-frontend/build.rs

feat: auto startup

---

tachyon-frontend/build.rs

fix: build script should detect .tmp

---

.github/workflows/coverage.yml
entity/Cargo.toml
entity/src/lib.rs
entity/src/object.rs
entity/src/user.rs
migration/Cargo.toml
migration/src/lib.rs
migration/src/m20220101_000002_create_user_table.rs
tachyon-core/Cargo.toml
tachyon-core/misc/config.toml
tachyon-core/src/main.rs
tachyon-core/src/routers/api/hello_world.rs
tachyon-core/src/routers/api/mod.rs
tachyon-core/src/routers/api/user.rs
tachyon-core/src/state.rs
tachyon-core/src/test/utils.rs
tachyon-frontend/src/auth/auth.ts
tachyon-template/src/lib.rs

feat: auth

---

entity/src/lib.rs
entity/src/task.rs
migration/src/lib.rs
migration/src/m20220101_000003_create_task_table.rs

Signed-off-by: Polo <119010079@link.cuhk.edu.cn>

feat: add task table

---

.github/workflows/cargo.yml
.github/workflows/clippy.yml
.github/workflows/coverage.yml
entity/Cargo.toml
entity/src/user.rs
tachyon-core/Cargo.toml
tachyon-core/src/main.rs
tachyon-core/src/routers/api/user.rs
tachyon-core/src/session.rs
tachyon-core/src/test/utils.rs
tachyon-docker/Dockerfile

feat: add more test for user system

---

tachyon-core/src/main.rs
tachyon-core/src/routers/mod.rs
tachyon-core/src/routers/view/error.rs
tachyon-core/src/routers/view/mod.rs
tachyon-core/src/test/utils.rs
tachyon-core/src/utils.rs
tachyon-template/src/error.rs
tachyon-template/src/index.rs
tachyon-template/src/lib.rs
tachyon-template/templates/error.stpl
tachyon-template/templates/index.stpl

feat: error handler

---

.github/workflows/coverage.yml

Signed-off-by: HaotianXie <hotinexie@gmail.com>

ci: add `+nightly` for cargo in coverage

---

tachyon-core/misc/config.toml
tachyon-core/src/configs.rs
tachyon-core/src/main.rs
tachyon-docker/Dockerfile

chore: move log level into config.toml

---

migration/src/m20220101_000005_add_user_tsvector.rs

fix: fix typo in migration file

---

tachyon-core/src/routers/view/user.rs
tachyon-template/templates/view/user.stpl

fix: resolve page overflow

---

tachyon-core/src/routers/api/object.rs

fix: obj deletion

---

entity/src/lib.rs
entity/src/task_discussion_attachment.rs
entity/src/task_user_assignment.rs
migration/src/lib.rs
migration/src/m20220101_000011_create_task_user_assignment_table.rs
migration/src/m20220101_000012_create_task_discussion_attachment_table.rs

Signed-off-by: HaotianXie <hotinexie@gmail.com>

feat: init task-user-assignment and task-discussion-attachment tabe

---

entity/src/task_user_assignment.rs
migration/src/m20220101_000011_create_task_user_assignment_table.rs

Signed-off-by: HaotianXie <hotinexie@gmail.com>

fix: fix typo

---

entity/src/user.rs
tachyon-core/src/routers/view/task.rs

Signed-off-by: HaotianXie <hotinexie@gmail.com>
Co-authored-by: Schrodinger ZHU Yifan <i@zhuyi.fan>

feat: add more task functions

---

tachyon-core/src/routers/view/task.rs
tachyon-frontend/src/main.ts
tachyon-template/templates/view/task.stpl
tachyon-template/templates/view/user.stpl

fix: some fixes for basic functions

---

tachyon-core/src/routers/api/mod.rs
tachyon-core/src/routers/api/user.rs
tachyon-frontend/src/main.ts
tachyon-template/templates/view/user.stpl

feat: user addition

---

tachyon-core/src/routers/api/user.rs

chore: fmt

---

tachyon-core/src/routers/view/user.rs

fix: 500 error in tsquery

---

entity/src/user.rs
tachyon-core/src/routers/api/mod.rs
tachyon-core/src/routers/api/user.rs
tachyon-frontend/src/main.ts
tachyon-template/templates/view/user.stpl

feat: user edit

---

migration/src/lib.rs
migration/src/m20220101_000014_add_task_tsvector.rs
tachyon-core/src/routers/view/task.rs
tachyon-frontend/src/main.ts
tachyon-template/src/view/task.rs
tachyon-template/templates/view/task.stpl

feat: task search

---

tachyon-core/src/routers/api/mod.rs
tachyon-core/src/routers/api/task.rs
tachyon-frontend/src/main.ts
tachyon-template/templates/view/task_detail.stpl

Signed-off-by: Polo <119010079@link.cuhk.edu.cn>

feat: add resolve and delete for task

---

tachyon-core/Cargo.toml
tachyon-core/src/configs.rs
tachyon-core/src/routers/api/task.rs
tachyon-core/src/routers/api/user.rs
tachyon-core/src/state.rs
tachyon-frontend/src/main.ts
tachyon-template/src/lib.rs

feat: email

---

tachyon-core/Cargo.toml
tachyon-core/misc/config.toml
tachyon-core/src/configs.rs
tachyon-core/src/routers/api/user.rs
tachyon-core/src/state.rs
tachyon-core/src/utils.rs

feat: prepare for pre

---

tachyon-core/src/routers/api/task.rs
tachyon-core/src/routers/api/user.rs
tachyon-core/src/routers/mod.rs
tachyon-core/src/routers/view/mod.rs
tachyon-core/src/state.rs
tachyon-core/src/test/utils.rs

ci: improve cov
